
# {{{ health checkers
### profiles - users - auth
GET http://localhost:8001/health

GET http://localhost:8002/health

GET http://localhost:8003/health

### fmc
GET http://localhost:8005/health

### questions - answers
GET http://localhost:8011/health

GET http://localhost:8012/health

### modules
GET http://localhost:8021/health

### resources - papers
GET http://localhost:8031/health

GET http://localhost:8032/health

### local
GET http://localhost:8000/health
# }}}

### auth bypass
GET http://localhost:8003/auth/bypass/1
Accept: application/json

# {{{ slides

GET http://localhost:8000/api/v1/slide
Accept: application/json
Authorization: Bearer 

GET http://localhost:8000/api/v1/slide/1
Accept: application/json
Authorization: Bearer 

POST http://localhost:8000/api/v1/slide/multiple
Accept: application/json
Authorization: Bearer 
Content-Type: application/json

[ 1, 2, 8 ]

POST http://localhost:8000/api/v1/slide
Accept: application/json
Authorization: Bearer 
Content-Type: application/json

{
  "slide_type": "content",
  "title": "Título tropecientos"
}

GET http://localhost:8000/api/v1/slide/3
Accept: application/json
Authorization: Bearer 

PUT http://localhost:8000/api/v1/slide/3
Accept: application/json
Authorization: Bearer 
Content-Type: application/json

{
  "slide_type": "content",
  "media": {
    "name": "Super imagen",
    "media_type": "image",
    "url": "http://google.com/"
  },
  "content": "Content del título tropecientos",
  "title": "Título tropecientos"
}

# }}}
